# Generated by Django 5.2.5 on 2025-08-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
